<?php

namespace App\Console\Commands;

use App\Services\Database;
use App\Support\PortfolioContent;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

#[Signature('portfolio:export')]
#[Description('Export the portfolio content (settings, services, projects, experience, skills) into seeder data files')]
class ExportPortfolioContent extends Command
{
    /**
     * Write every content table to database/seeders/data/<table>.php.
     */
    public function handle(): int
    {
        File::ensureDirectoryExists(dirname(PortfolioContent::dataPath('settings')));

        foreach (array_keys(PortfolioContent::TABLES) as $table) {
            $orderBy = $table === 'settings' ? 'key' : 'id';
            $rows = array_map(
                fn (object $row): array => PortfolioContent::fromDatabaseRow($table, (array) $row),
                Database::query("SELECT * FROM {$table} ORDER BY {$orderBy} ASC")
            );

            $source = "<?php\n\n// Generated by `php artisan portfolio:export` — edit content in the admin, then re-export.\n\nreturn "
                .PortfolioContent::toPhp($rows).";\n";

            File::put(PortfolioContent::dataPath($table), $source);
            $this->components->twoColumnDetail($table, count($rows).' rows');
        }

        $this->newLine();
        $this->components->info('Content exported to database/seeders/data. Commit these files, then run `php artisan portfolio:seed` on the server.');

        return self::SUCCESS;
    }
}
