<?php

// Generated by `php artisan portfolio:export` — edit content in the admin, then re-export.

return [
    [
        'id' => 1,
        'name' => 'Backend Development',
        'icon' => '⚙️',
        'type' => 'bars',
        'sort_order' => 0,
        'created_at' => '2026-07-18 11:36:16',
        'updated_at' => '2026-07-18 11:36:16',
        'name_ar' => 'تطوير Backend',
    ],
    [
        'id' => 2,
        'name' => 'Database & Caching',
        'icon' => '🗄️',
        'type' => 'bars',
        'sort_order' => 1,
        'created_at' => '2026-07-18 11:36:16',
        'updated_at' => '2026-07-18 11:36:16',
        'name_ar' => 'قواعد البيانات والتخزين المؤقت',
    ],
    [
        'id' => 3,
        'name' => 'DevOps & Tools',
        'icon' => '🚀',
        'type' => 'bars',
        'sort_order' => 2,
        'created_at' => '2026-07-18 11:36:16',
        'updated_at' => '2026-07-18 11:36:16',
        'name_ar' => 'DevOps والأدوات',
    ],
    [
        'id' => 4,
        'name' => 'Frontend & Other',
        'icon' => '🎨',
        'type' => 'tags',
        'sort_order' => 3,
        'created_at' => '2026-07-18 11:36:16',
        'updated_at' => '2026-07-18 11:36:16',
        'name_ar' => 'الواجهة الأمامية وأخرى',
    ],
];
